//go:build ignore

// confusables_gen writes latin_confusables.txt, the fold table Normalize
// embeds: every entry of Unicode's confusables.txt whose target is plain
// Latin letters or digits (combining marks on the target dropped), plus a
// short supplement of look-alikes the file lacks (small capitals), plus the
// lower case of every capital source without a row of its own.
//
// Regenerate (only when Unicode publishes a new file):
//
//	curl -sSo /tmp/confusables.txt https://www.unicode.org/Public/security/latest/confusables.txt
//	go run confusables_gen.go -in /tmp/confusables.txt
package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"maps"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// supplement: Latin small capitals and other letter-like runes that
// confusables.txt does not map (or maps to a non-ASCII letter), source → target.
var supplement = map[rune]string{
	'ᴀ': "a", 'ʙ': "b", 'ᴄ': "c", 'ᴅ': "d", 'ᴇ': "e", 'ꜰ': "f", 'ɢ': "g", 'ʜ': "h", 'ɪ': "i", 'ᴊ': "j",
	'ᴋ': "k", 'ʟ': "l", 'ᴍ': "m", 'ɴ': "n", 'ᴏ': "o", 'ᴘ': "p", 'ꞯ': "q", 'ʀ': "r", 'ꜱ': "s", 'ᴛ': "t",
	'ᴜ': "u", 'ᴠ': "v", 'ᴡ': "w", 'ʏ': "y", 'ᴢ': "z", 'ĸ': "k",
}

func main() {
	in := flag.String("in", "", "path to Unicode confusables.txt")
	out := flag.String("out", "latin_confusables.txt", "output table")
	flag.Parse()
	f, err := os.Open(*in)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	table := map[rune]string{}
	header := ""
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimPrefix(sc.Text(), "\uFEFF")
		if strings.HasPrefix(line, "# Date:") || strings.HasPrefix(line, "# Version:") {
			header += line + "\n"
		}
		if line == "" || line[0] == '#' {
			continue
		}
		parts := strings.Split(line, ";")
		if len(parts) < 3 {
			continue
		}
		src, err := strconv.ParseUint(strings.TrimSpace(parts[0]), 16, 32)
		if err != nil {
			continue
		}
		target, ok := latin(strings.Fields(parts[1]))
		if !ok || target == string(rune(src)) {
			continue
		}
		table[rune(src)] = target
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}
	for r, t := range supplement {
		table[r] = t
	}
	// Normalize looks a rune up after lower-casing it, so a capital's
	// confusable must also be reachable from its lower-case form (Cyrillic
	// М → м): add the lower case of every capital source that has no row of
	// its own, mapped to the lower case of the capital's target.
	for r, t := range maps.Clone(table) {
		if lo := unicode.ToLower(r); lo != r {
			if _, ok := table[lo]; !ok {
				table[lo] = strings.ToLower(t)
			}
		}
	}
	keys := make([]rune, 0, len(table))
	for r := range table {
		keys = append(keys, r)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	var b strings.Builder
	b.WriteString("# Generated by confusables_gen.go from Unicode confusables.txt (Latin targets only) plus its supplement. DO NOT EDIT.\n")
	for _, l := range strings.Split(strings.TrimSpace(header), "\n") {
		b.WriteString(l + "\n")
	}
	b.WriteString("# source<TAB>target, hex code point → ASCII letters/digits\n")
	for _, r := range keys {
		fmt.Fprintf(&b, "%04X\t%s\n", r, table[r])
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("%d entries", len(keys))
}

// latin is the target as ASCII letters and digits, combining marks
// (U+0300–U+036F) dropped; false when anything else remains.
func latin(hex []string) (string, bool) {
	var b strings.Builder
	for _, h := range hex {
		v, err := strconv.ParseUint(h, 16, 32)
		if err != nil {
			return "", false
		}
		r := rune(v)
		switch {
		case r >= 0x300 && r <= 0x36F:
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			return "", false
		}
	}
	return b.String(), b.Len() > 0
}
